[package]
name = 'embedded-core'
version = '0.1.0'
edition = '2024'

[lib]
crate-type = ['rlib', 'staticlib', 'cdylib']
name = 'surrealdb_embedded'

[dependencies]
surrealdb = { version = '3.0.1', default-features = false, features = ['kv-mem', 'kv-surrealkv'] }
tokio = { version = '1', features = ['rt', 'macros'] }
